### ISSUE TITLE
Not an issue but a req. UsnJrnl

### ISSUE THREAD

**Issue by gunner4361** [dfir-scripts/siftgrab#2]
Would be great if it would parse the UsnJrnl

**Comment by dfir-scripts** [comment]
Earlier versions had a built-in USNJRNL parser using options 2. Because USN parsing is sometimes slow, I removed the function and added an option to the  Additional Parsers sub menu where you can parse it manually using  ntfs_parser.   The original parser I was using, usn.py  is also still installed.    What I will do in the next update is add the function back in to the main parser and then provide an easy way to enable or disable it.
